name: cc_tests

on:
  push:
    branches:
      - jp-test-bb
  pull_request:

jobs:
  cctests:
    name: cc_tests
    runs-on: ubuntu-18.04
    timeout-minutes: 120
    container:
      image: envoyproxy/envoy-build-ubuntu:0a02a76af5951bf7f4c7029c0ea6d29d96c0f682
    steps:
      - uses: actions/checkout@v1
        with:
          submodules: true
      - name: Add safe directory
        run: git config --global --add safe.directory /__w/envoy-mobile/envoy-mobile
      - env:
            BUILDBUDDY_API_KEY: ${{ secrets.BUILDBUDDY_API_KEY }}
        name: 'Run tests'
        run: ./bazelw test --action_env=LD_LIBRARY_PATH --test_output=all --config=remote-ci-linux --remote_header="x-buildbuddy-api-key=$BUILDBUDDY_API_KEY" //test/cc/...
